<a href="https://colab.research.google.com/github/angui100/Tensorflow_certificate/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [92]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [93]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [94]:
data_file = '/content/drive/My Drive/datasource/Churn_Modelling.csv'
data_set = pd.read_csv( data_file )
print(data_set)

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10

Data analyze part
## 1. independent variables

In [95]:
X = data_set.iloc[:, 3:-1].values
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


## 2. Dependent variables

In [96]:
y = data_set.iloc[:, -1].values
print(y)

[1 0 1 ... 1 1 0]


## 3. Need to fix any missing data?

### Encoding categorical data

Label Encoding the "Gender" column

In [97]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [98]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer( transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

print(type(X))
print(X)


<class 'numpy.ndarray'>
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Convert the numpy.ndarray to numpy array ? Answer: Not needed here.

In [99]:
X = np.array(X) # ? Really need to convert to Numpy array
print(type(X))

<class 'numpy.ndarray'>


### Splitting the dataset into the Training set and Test set

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [101]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [102]:
print(len(X_train))
print(X[-1, :])

8000
[1.0 0.0 0.0 792 0 28 4 130142.79 1 1 0 38190.78]


In [103]:
print(X_test[-1, :])

[0.0 1.0 0.0 573 1 30 8 127406.5 1 1 0 192950.6]


In [104]:
print(len(X_test))

2000


### Feature Scaling (Very Important)
Need to determine what are the columns of data need to be standarlized in this model.

In [105]:
print(X_test[-1, :]) #The las row of data
print(X_test[:, 4:])

[0.0 1.0 0.0 573 1 30 8 127406.5 1 1 0 192950.6]
[[0 35 8 ... 1 1 192852.67]
 [0 40 2 ... 1 0 128702.1]
 [0 42 8 ... 1 1 75732.25]
 ...
 [1 36 1 ... 1 0 141533.19]
 [1 34 4 ... 1 1 11276.48]
 [1 30 8 ... 1 0 192950.6]]


From the last row of data, we do see there are 3 columns may need to be standarlized for this model. Which are indexes [4], [8], [12]
<br>In order to standarlize the related data, do we need to rearrange the columns of the dataframe ???

In [106]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
#X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])
X_train = sc.fit_transform(X_train)

In [107]:
print(X_train[-1:, :])

[[-1.01460667  1.75486502 -0.57369368 -0.28401079 -1.09168714  0.87525072
  -1.37744033  0.5113635  -0.92159124  0.64259497 -1.03227043  0.32472465]]


In [108]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [109]:
print(X_train[1, :])

[-1.01460667  1.75486502 -0.57369368 -2.30455945  0.91601335  0.30102557
 -1.37744033 -0.00631193 -0.92159124  0.64259497  0.9687384  -0.74866447]


In [111]:
X_test = sc.transform(X_test)
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [112]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


## Part 2 - Building the ANN

### Initializing the ANN

In [113]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [114]:
ann.add( tf.keras.layers.Dense(units=6, activation='relu' ))

### Adding the second hidden layer

In [115]:
ann.add(tf.keras.layers.Dense( units=6, activation='relu'))

### Adding the output layer

In [116]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [117]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [121]:
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)
X_test = np.asarray(X_test).astype(np.float32)
y_test = np.asarray(y_test).astype(np.float32)
ann.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test), validation_steps=20)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3335 - accuracy: 0.8621 - val_loss: 0.3159 - val_accuracy: 0.8766
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8620 - val_loss: 0.3136 - val_accuracy: 0.8781
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8621 - val_loss: 0.3176 - val_accuracy: 0.8687
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8625 - val_loss: 0.3155 - val_accuracy: 0.8719
Epoch 5/100
250/250 [==============================] - 0s 997us/step - loss: 0.3340 - accuracy: 0.8631 - val_loss: 0.3165 - val_accuracy: 0.8719
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8630 - val_loss: 0.3182 - val_accuracy: 0.8719
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8644 - val_loss: 0.3166 - val_accuracy: 0.87

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [124]:
x =[ [1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000] ]
x = sc.transform(x)
#x = [[1, 0, 0, 6.e+02 1.e+00 4.e+01 3.e+00 6.e+04 2.e+00 1.e+00 1.e+00 5.e+04]]
#print(x)
#x = np.asarray(x).astype(np.float32)
#print(x)
#x = sc.transform([[x]])
print(ann.predict(x) )
print(ann.predict(x) > 0.5)

[[0.01851797]]
[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [125]:
y_pred = ann.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.5)
print(y_pred)

[[0.22864366]
 [0.31802973]
 [0.20073876]
 ...
 [0.163836  ]
 [0.16963482]
 [0.1971643 ]]
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [132]:
print(np.concatenate( (y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [133]:
print(y_pred.reshape(len(y_pred), 1))

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [134]:
print(y_test.reshape(len(y_test), 1))

[[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


### Making the Confusion Matrix

In [136]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1500   95]
 [ 185  220]]


In [137]:
accuracy_score(y_test, y_pred)

0.86